const ge_mri_gesys_schema = {
  system_id: null,
  epoch: null,
  record_number_concurrent: null,
  misc_param_1: null,
  month: null,
  day: null,
  host_date: null,
  host_time: null,
  year: null,
  message_number: null,
  misc_param_2: null,
  type: null,
  data_1: null,
  num_1: null,
  server: null,
  task_id: null,
  task_epoc: null,
  object: null,
  exception_class: null,
  severity: null,
  function: null,
  psd: null,
  coil: null,
  scan: null,
  message: null,
  sr: null,
  en: null,
  host_datetime: null,
  capture_datetime: null
};

const ge_ct_gesys_schema = {
  system_id: null,
  epoch: null,
  record_number_concurrent: null,
  misc_param_1: null,
  month: null,
  day: null,
  host_date: null,
  host_time: null,
  year: null,
  message_number: null,
  misc_param_2: null,
  type: null,
  data_1: null,
  num_1: null,
  date_2: null,
  host: null,
  ermes_number: null,
  exception_class: null,
  severity: null,
  file: null,
  line_number: null,
  scan_type: null,
  warning: null,
  end_msg: null,
  message: null,
  sr: null,
  en: null,
  host_datetime: null,
  capture_datetime: null
};

const ge_cv_syserror_schema = {
  system_id: null,
  sequencenumber: null,
  host_date: null,
  host_time: null,
  subsystem: null,
  errorcode: null,
  errortext: null,
  exam: null,
  exceptioncategory: null,
  application: null,
  majorfunction: null,
  minorfunction: null,
  fru: null,
  viewinglevel: null,
  rootcause: null,
  repeatcount: null,
  debugtext: null,
  sourcefile: null,
  sourceline: null,
  host_datetime: null,
  capture_datetime: null
};

module.exports = {
  ge_mri_gesys_schema,
  ge_ct_gesys_schema,
  ge_cv_syserror_schema
};
